generate:
  models:
    names: [cyclegan]

    weights: [models/cyclegan_he2mt.pth]


  data_path: data/he/
  a2b: true
  batch_size: 32
  results_path: results/masson_fake/
  add_suffix: false
  device: 0
  num_workers: 4
  center_crop: false # 256


